[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "aml-labs"
platforms = ["linux-64", "win-64"]

# [system-requirements]
# cuda = "12.0"

[tasks]
server = "jupyter server"

[dependencies]
python = ">=3.13.3,<3.14"
jupyter = ">=1.1.1,<2"
pytorch = ">=2.6.0,<3"
# pytorch-gpu = "*"
torchvision = ">=0.21.0,<0.22"
