[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "aml-labs"
platforms = ["linux-64", "win-64"]

[tasks]
server = "jupyter server"
check-diff = "git diff upstream/develop upstream/develop~1 > diff.patch"
apply-diff = "patch -R -p1 < diff.patch"

[dependencies]
python = ">=3.13.3,<3.14"
jupyter = ">=1.1.1,<2"
pytorch = ">=2.6.0,<3"
# pytorch-gpu = "*"
torchvision = ">=0.21.0,<0.22"


[environments]
nb-diff = ["nb-diff"]
gpu = ["gpu"]

[feature.nb-diff.dependencies]
nbdime = "*"

[feature.nb-diff.tasks]
setup-diff = "nbdime config-git --enable"

[feature.gpu.dependencies]
pytorch-gpu = "*"

[feature.gpu.system-requirements]
cuda = "12.0"